name: krettel-app
app_id: da_R4qIGtmUDA9Y
owner: slashcutz_official
package: .
env:
  APP_KEY: base64:A/zA43K6XN1JzKqCtrpfucXFxEw2guTB6MDSkyYhiMo=
  APP_ENV: production
  APP_DEBUG: 'true'
  APP_URL: https://krettel-app.wasmer.app
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  FILESYSTEM_DISK: local
  SESSION_DRIVER: file
  CACHE_STORE: file
  QUEUE_CONNECTION: database
  DB_CONNECTION: sqlite
  DB_DATABASE: /app/storage/database.sqlite
  TERABOX_REMOTE_DIR: /Apps/Krettel
  TERABOX_WEB_HOST: https://www.1024terabox.com
  PIXELDRAIN_BASE_URL: https://pixeldrain.net
  PIXELDRAIN_STREAM_MODE: redirect
  R2_ENABLED: 'true'
  R2_ACCOUNT_ID: 3e85fadf9a1a079abc34d060ad920a36
  R2_ACCESS_KEY_ID: b6c6bc75524a6bf167e3bae6600749b1
  R2_SECRET_ACCESS_KEY: 0f9048fa7087dbb509ccdbab75fb9c586bd53961421c9f2f532fecf873e8bcee
  R2_BUCKET: krettel
  R2_ENDPOINT: ''
  R2_PRESIGN_EXPIRY: '3600'
  DB_BUSY_TIMEOUT: '120000'
  DB_JOURNAL_MODE: 'WAL'
  DB_SYNCHRONOUS: 'NORMAL'
  PHPIX_PHP_THREADS: '2'
volumes:
- name: storage
  mount: /app/storage
jobs:
- name: setup-migrate
  trigger: post-deployment
  action:
    execute:
      command: migrate
- name: setup-storage-link
  trigger: post-deployment
  action:
    execute:
      command: storage-link
- name: setup-seed-admin
  trigger: post-deployment
  action:
    execute:
      command: seed-admin
- name: process-queue
  trigger: '*/5 * * * *'
  action:
    execute:
      command: process-queue
kind: wasmer.io/App.v0
